### PR TITLE
docs: update swaggerui docs

### PR DESCRIPTION
**Pull request by blaketingyu**
- [x] : Split the API routes based on services
- [x] : Provided example inputs for the question services parameters

### CODE REVIEW

**Comment by blaketingyu** [comment]
IMAGE 2022-10-23 00:54:53

**Comment by blaketingyu** [comment]
IMAGE 2022-10-23 00:55:21

**Review by yusufaine — APPROVED** [review]
LGTM!

**Review by aidanaden — APPROVED** [review]
lgtm - potential improvement is to use the zod generated types when manually adding the class dtos, e.g.
```
type QuestionQueryType = z.infer<typeof QuestionQuerySchema>;
type titleSlugType = QuestionQueryType[""];

@IsOptional()
@IsString({ each: true })
@ApiPropertyOptional({
  type: [String],
  description: "Title slug associated to question",
})
public titleSlugs: titleSlugType;
```

**Pull request merged**
